import css from '@webref/css/css.json' with { type: 'json' };

/**
 * Builds `src/property-groups.js` from the CSS specifications. Run
 * `npm run generate` after an update of `@webref/css`.
 */

// Browser aliases that no specification defines, without a vendor prefix
/** @type {ReadonlyArray<[string, string]>} */
const browserAliases = [
  ['logical-width', 'inline-size'],
  ['logical-height', 'block-size'],
  ['column-break-before', 'break-before'],
  ['column-break-after', 'break-after'],
  ['column-break-inside', 'break-inside'],
  ['page-break-before', 'break-before'],
  ['page-break-after', 'break-after'],
  ['page-break-inside', 'break-inside'],
  ['glyph-orientation-vertical', 'text-orientation'],
  ['box-flex', 'flex-grow'],
  ['box-orient', 'flex-direction'],
  ['box-direction', 'flex-direction'],
  ['box-ordinal-group', 'order'],
  ['box-align', 'align-items'],
  ['box-pack', 'justify-content'],
];

/**
 * @return {Map<string, string>} each property that shares a value with
 *   another one, and the name of its group
 */
function getPropertyGroups() {
  /** @type {Map<string, string>} */
  const parents = new Map();
  /**
   * @param {string} name - property or group name
   * @return {string} the root of its set
   */
  const getRoot = (name) => {
    let root = name;
    for (
      let parent = parents.get(root);
      parent !== undefined && parent !== root;
      parent = parents.get(root)
    ) {
      root = parent;
    }
    parents.set(name, root);
    return root;
  };
  /**
   * @param {string} first - property or group name
   * @param {string} second - property or group name
   * @return {undefined}
   */
  const join = (first, second) => {
    parents.set(getRoot(first), getRoot(second));
  };

  for (const property of css.properties) {
    const related = [
      ...('longhands' in property ? property.longhands : []),
      ...('resetLonghands' in property ? property.resetLonghands : []),
      ...('legacyAliasOf' in property ? [property.legacyAliasOf] : []),
    ];
    for (const name of related) join(property.name, name);
    if ('logicalPropertyGroup' in property) {
      // A space keeps the group's name apart from every property name
      join(property.name, `logical ${property.logicalPropertyGroup}`);
    }
  }
  for (const [alias, name] of browserAliases) join(alias, name);

  /** @type {Map<string, Array<string>>} */
  const members = new Map();
  for (const name of parents.keys()) {
    if (name.includes(' ')) continue;
    const root = getRoot(name);
    members.set(root, [...(members.get(root) ?? []), name]);
  }
  /** @type {Map<string, string>} */
  const groups = new Map();
  for (const names of members.values()) {
    names.sort(
      (first, second) =>
        first.length - second.length || (first < second ? -1 : 1),
    );
    const [group = ''] = names;
    for (const name of names) groups.set(name, group);
  }
  return new Map(
    [...groups].sort(([first], [second]) => (first < second ? -1 : 1)),
  );
}

/**
 * @return {string} the text of `src/property-groups.js`
 */
export function getPropertyGroupsSource() {
  const groups = getPropertyGroups();
  const entries = [...groups].map(
    ([name, group]) => `  ['${name}', '${group}'],\n`,
  );
  const segments = Math.max(
    ...[...groups.keys()].map((name) => name.split('-').length),
  );
  return `// Generated by test/_property-groups.js; run \`npm run generate\` to update

/**
 * Properties that set a value another property also sets: a shorthand and its
 * longhands, an alias and its target, and physical and logical properties.
 * Each maps to the name of its group.
 * @type {ReadonlyMap<string, string>}
 */
export const propertyGroups = new Map([
${entries.join('')}]);

/** The most name parts, split at hyphens, of a property in the map */
export const propertyGroupSegments = ${String(segments)};
`;
}
