extends:
  - google
  - plugin:import/errors
  - plugin:import/warnings
  - plugin:node/recommended
plugins:
  - import
  - markdown
  - node
rules:
  node/no-missing-require:
    - error
    - allowModules:
      - postcss-combine-duplicated-selectors
  node/no-unpublished-require:
    - error
    - allowModules:
      - postcss-combine-duplicated-selectors
  node/no-unsupported-features:
    - error
    - version: 4
      ignores:
        - modules
