parserOptions:
  ecmaVersion: 8
  sourceType: module
extends:
  - google
  - plugin:import/errors
  - plugin:import/warnings
  - plugin:node/recommended
plugins:
  - import
  - markdown
  - node
rules:
  # Javascript feature preference
  no-var: error
  prefer-arrow-callback: error
  prefer-const: error
  prefer-template: error

  # Node.js feature configuration
  node/no-missing-require:
    - error
    - allowModules:
      - postcss-combine-duplicated-selectors
  node/no-unpublished-require:
    - error
    - allowModules:
      - postcss-combine-duplicated-selectors
  node/no-unsupported-features:
    - error
    - version: 4
      ignores:
        - modules
