environment:
  matrix:
    - nodejs_version: 6
    - nodejs_version: 8

init:
  - git config --global core.autocrlf true

install:
  - ps: Install-Product node $env:nodejs_version
  - npm install

test_script:
  - node --version
  - npm --version
  - npm test

build: off
